# Generated by Django 5.1.3 on 2024-11-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinoepoca',
            options={'ordering': ['nome'], 'verbose_name': 'Época', 'verbose_name_plural': 'Épocas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Dinossauro', 'verbose_name_plural': 'Dinossauros'},
        ),
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='images/')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinodieta')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinoepoca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinotipodedino')),
            ],
        ),
    ]
