# Generated by Django 5.1.3 on 2024-11-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_dinoepoca_options_alter_post_options_dino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dinoImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
